/**
 * Created by itay on 19/06/17.
 */
const LEFT_SIDE_GO_CLICKED = 'LEFT_SIDE_GO';
const LEFT_SIDE_RESULT_CLICKED = 'LEFT_SIDE_RESULT_CLICKED';
const LEFT_SIDE_NEXT_BUTTON_CLICKED = 'LEFT_SIDE_NEXT_BUTTON_CLICKED';
const LEFT_SIDE_LIST_BUTTON_CLICKED = 'LEFT_SIDE_LIST_BUTTON_CLICKED';
const LEFT_SIDE_TILE_BUTTON_CLICKED = 'LEFT_SIDE_TILE_BUTTON_CLICKED';