/**
 * Created by itay on 19/06/17.
 */
export const LEFT_SIDE_GO_CLICKED = 'LEFT_SIDE_GO_CLICKED';
export const LEFT_SIDE_RESULT_CLICKED = 'LEFT_SIDE_RESULT_CLICKED';
export const LEFT_SIDE_NEXT_BUTTON_CLICKED = 'LEFT_SIDE_NEXT_BUTTON_CLICKED';
export const LEFT_SIDE_LIST_BUTTON_CLICKED = 'LEFT_SIDE_LIST_BUTTON_CLICKED';
export const LEFT_SIDE_TILE_BUTTON_CLICKED = 'LEFT_SIDE_TILE_BUTTON_CLICKED';
export const LEFT_SIDE_TRACK_LIST_RECEIVED = 'LEFT_SIDE_TRACK_LIST_RECEIVED';